"""Nonce labels, the frozen label-set store, and the prompt leakage guard.

SPEC §5.3 (labels) and §5.6 (denylist). Label sets are fixed across seeds (R4):
they are generated once, frozen in data/label_sets.json with a hash, and never
regenerated by a run.
"""
from __future__ import annotations

import hashlib
import json
import re
from functools import lru_cache
from pathlib import Path

import numpy as np

DATA_DIR = Path(__file__).resolve().parent / "data"
LABEL_STORE = DATA_DIR / "label_sets.json"

CONSONANTS = "bdfgklmnprstvz"
VOWELS = "aeiou"

# ---------------------------------------------------------------- denylist --
# Word-boundary, case-insensitive. A trailing \w* implements the "agree*" stems.
DENY_PATTERNS_ALWAYS = [
    r"consensus", r"agree\w*", r"disagree\w*", r"coordinat\w*", r"cooperat\w*",
    r"align\w*", r"success\w*", r"fail\w*", r"common language", r"converge\w*",
    r"the group", r"majority", r"most", r"popular", r"winning", r"collective",
    r"everyone", r"population", r"other participants",
]
DENY_REGEX_ALWAYS = [r"\d+\s*(?:agents|participants|%)"]
DENY_PATTERNS_REWARD_OFF = [r"points?", r"score\w*", r"reward\w*", r"payoffs?", r"win", r"lose"]

# Plain substrings a label may not contain (label hygiene, test 15).
DENY_SUBSTRINGS = [
    "consensus", "agree", "coordinat", "cooperat", "align", "success", "fail",
    "converge", "group", "majority", "most", "popular", "win", "collective",
    "everyone", "population", "point", "score", "reward", "payoff", "lose",
]


def _compile(words):
    return [re.compile(rf"\b{w}\b", re.IGNORECASE) for w in words]


_ALWAYS = _compile(DENY_PATTERNS_ALWAYS) + [re.compile(p, re.IGNORECASE) for p in DENY_REGEX_ALWAYS]
_REWARD_OFF = _compile(DENY_PATTERNS_REWARD_OFF)


def guard_prompt(prompt: str, reward_on: bool) -> list[str]:
    """Return the denylist hits in a rendered prompt (empty list = clean)."""
    hits = []
    for rx in _ALWAYS + ([] if reward_on else _REWARD_OFF):
        for m in rx.finditer(prompt):
            hits.append(m.group(0))
    return hits


# ---------------------------------------------------------------- wordlists --
@lru_cache(maxsize=None)
def _wordlist(name: str) -> frozenset:
    path = DATA_DIR / name
    if not path.exists():
        return frozenset()
    return frozenset(w.strip().lower() for w in path.read_text().splitlines() if w.strip())


def english_words() -> frozenset:
    return _wordlist("english_words.txt")


def first_names() -> frozenset:
    return _wordlist("first_names.txt")


def brands() -> frozenset:
    return _wordlist("brands.txt")


# ---------------------------------------------------------------- rules --
def levenshtein(a: str, b: str) -> int:
    a, b = a.lower(), b.lower()
    prev = list(range(len(b) + 1))
    for i, ca in enumerate(a, 1):
        cur = [i]
        for j, cb in enumerate(b, 1):
            cur.append(min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (ca != cb)))
        prev = cur
    return prev[-1]


def _has_alpha_sequence(w: str) -> bool:
    w = w.lower()
    for i in range(len(w) - 2):
        a, b, c = (ord(x) for x in w[i:i + 3])
        if (b - a == 1 and c - b == 1) or (a - b == 1 and b - c == 1):
            return True
    return False


def label_problems(label: str) -> list[str]:
    """Why a single candidate label is rejected (empty = acceptable)."""
    w = label.lower()
    p = []
    if w in english_words():
        p.append("english word")
    if w in first_names():
        p.append("first name")
    if w in brands():
        p.append("brand")
    for s in DENY_SUBSTRINGS:
        if s in w:
            p.append(f"denylist substring {s!r}")
    if _has_alpha_sequence(w):
        p.append("alphabetical sequence")
    if len(w) >= 4 and w[:2] == w[2:4]:
        p.append("reduplicated syllable")
    return p


def set_problems(labels: list[str]) -> list[str]:
    """Why a label set violates SPEC §5.3 (empty = passes)."""
    p = []
    for lab in labels:
        for why in label_problems(lab):
            p.append(f"{lab}: {why}")
    for i, a in enumerate(labels):
        for b in labels[i + 1:]:
            if levenshtein(a, b) < 2:
                p.append(f"{a}/{b}: edit distance < 2")
            if a[:2].lower() == b[:2].lower():
                p.append(f"{a}/{b}: same first two letters")
    if len({lab.lower() for lab in labels}) != len(labels):
        p.append("duplicate labels")
    return p


def _candidate(rng: np.random.Generator, pattern: str) -> str:
    out = []
    for ch in pattern:
        pool = CONSONANTS if ch == "C" else VOWELS
        out.append(pool[rng.integers(len(pool))])
    return "".join(out).title()


def generate_label_set(generator_seed: int, size: int = 10, pattern: str = "CVCV",
                       exclude: set[str] | None = None) -> list[str]:
    rng = np.random.default_rng(generator_seed)
    exclude = {x.lower() for x in (exclude or set())}
    chosen: list[str] = []
    for _ in range(100_000):
        cand = _candidate(rng, pattern)
        if cand.lower() in exclude or label_problems(cand):
            continue
        if any(levenshtein(cand, c) < 2 or cand[:2] == c[:2] for c in chosen):
            continue
        chosen.append(cand)
        if len(chosen) == size:
            return chosen
    raise RuntimeError("could not generate a label set; relax constraints")


def label_set_hash(labels: list[str]) -> str:
    return hashlib.sha256("\n".join(labels).encode()).hexdigest()


# ---------------------------------------------------------------- store --
def load_label_sets() -> dict:
    if not LABEL_STORE.exists():
        raise FileNotFoundError(LABEL_STORE)
    return json.loads(LABEL_STORE.read_text())


def get_labels(label_set_id: str) -> tuple[str, ...]:
    entry = load_label_sets()[label_set_id]
    labels = entry["labels"]
    if label_set_hash(labels) != entry["hash"]:
        raise ValueError(f"label set {label_set_id} does not match its frozen hash")
    return tuple(labels)


def freeze_label_sets(n_sets: int = 3, size: int = 10, base_seed: int = 20260924,
                      pattern: str = "CVCV", overwrite: bool = False) -> dict:
    """Generate and freeze label sets. Refuses to overwrite an existing store."""
    if LABEL_STORE.exists() and not overwrite:
        raise FileExistsError(f"{LABEL_STORE} already exists; label sets are frozen")
    store, used = {}, set()
    for i in range(n_sets):
        seed = base_seed + i
        labels = generate_label_set(seed, size, pattern, exclude=used)
        used |= {x.lower() for x in labels}
        store[f"L{i + 1}"] = {"labels": labels, "hash": label_set_hash(labels),
                              "generator_seed": seed, "pattern": pattern}
    LABEL_STORE.write_text(json.dumps(store, indent=2) + "\n")
    return store
